# Generated by Django 5.2.5 on 2025-08-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, unique=True)),
                ('task', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('data_collection_days', models.IntegerField(default=80)),
                ('collected_days', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='particular.divisionmodel')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='particular.projecttype')),
            ],
        ),
    ]
