# Generated by Django 5.2.5 on 2025-08-13 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('usage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='particular.task')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='particular.workequipment')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='equipments',
            field=models.ManyToManyField(related_name='tasks', through='particular.TaskEquipment', to='particular.workequipment'),
        ),
        migrations.AddField(
            model_name='particular',
            name='equipments',
            field=models.ManyToManyField(related_name='work_equipments', to='particular.workequipment'),
        ),
    ]
