# Generated by Django 5.2.5 on 2025-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0002_task_workequipment_taskequipment_task_equipments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workequipment',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workequipment',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
