# Generated by Django 5.2.5 on 2025-08-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0003_workequipment_count_workequipment_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivisionModel',
            new_name='Division',
        ),
    ]
