# Generated by Django 5.2.5 on 2025-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0004_rename_divisionmodel_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
