# Generated by Django 5.2.5 on 2025-08-23 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0005_alter_projecttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='particular',
            old_name='collected_days',
            new_name='collected_instances',
        ),
        migrations.RenameField(
            model_name='particular',
            old_name='data_collection_days',
            new_name='required_instances',
        ),
        migrations.RemoveField(
            model_name='particular',
            name='equipments',
        ),
        migrations.RemoveField(
            model_name='particular',
            name='id',
        ),
        migrations.AlterField(
            model_name='particular',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='particular_division', to='particular.division'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='pid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='particular',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='particular.projecttype'),
        ),
        migrations.AddField(
            model_name='division',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector', to='particular.sector'),
        ),
    ]
