# Generated by Django 5.2.5 on 2025-08-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0006_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='particular',
            name='equipments',
            field=models.ManyToManyField(related_name='work_equipments', to='particular.workequipment'),
        ),
    ]
