# Generated by Django 5.2.5 on 2025-08-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0007_particular_equipments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='sector',
        ),
        migrations.AddField(
            model_name='division',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsector', to='particular.projecttype'),
        ),
    ]
