# Generated by Django 5.2.5 on 2025-09-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0008_remove_division_sector_division_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workequipment',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
