# Generated by Django 5.2.5 on 2025-09-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0009_alter_workequipment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workequipment',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
