# Generated by Django 5.2.5 on 2025-08-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='_')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.engineer')),
            ],
        ),
        migrations.AlterField(
            model_name='tipperdatamodel',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collector'),
        ),
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_engieer', to='core.engineer'),
        ),
        migrations.DeleteModel(
            name='CollectorModel',
        ),
    ]
