# Generated by Django 5.2.5 on 2025-08-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_engineer_collector_alter_tipperdatamodel_collector_and_more'),
        ('particular', '0008_remove_division_sector_division_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('problems', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=15)),
                ('encoded', models.BooleanField(default=False)),
                ('encoder', models.CharField(max_length=255)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_collector', to='core.collector')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_particular', to='particular.particular')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instance_project', to='core.project')),
            ],
        ),
    ]
