# Generated by Django 5.2.5 on 2025-09-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_engineer_datainstance_encoded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainstance',
            name='problems',
        ),
    ]
