# Generated by Django 5.2.5 on 2025-09-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_datainstance_problems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datainstance',
            old_name='review_by',
            new_name='reviewed_by',
        ),
    ]
