# Generated by Django 5.2.5 on 2025-09-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_review_by_datainstance_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='projects',
            field=models.ManyToManyField(related_name='engineers', to='core.project'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
