# Generated by Django 5.2.5 on 2025-09-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_engineer_projects_alter_engineer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='project',
        ),
        migrations.AddField(
            model_name='collector',
            name='project',
            field=models.ManyToManyField(related_name='collectors', to='core.project'),
        ),
    ]
