# Generated by Django 5.2.5 on 2025-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_collector_project_collector_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='project',
            field=models.ManyToManyField(related_name='projects', to='core.project'),
        ),
    ]
