# Generated by Django 5.2.5 on 2025-09-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_collector_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='project',
            new_name='projects',
        ),
    ]
