# Generated by Django 5.2.5 on 2025-09-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_project_collector_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='projects',
            field=models.ManyToManyField(related_name='collectors', to='core.project'),
        ),
    ]
