# Generated by Django 5.2.5 on 2025-09-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_collector_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainstance',
            name='encoder',
        ),
    ]
