# Generated by Django 5.2.5 on 2025-09-09 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_equipment_problemcode_remove_mpdmcycle_mpdm_and_more'),
        ('particular', '0010_workequipment_equipment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('data_count', models.PositiveIntegerField(default=0)),
                ('number_of_equipment_types', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('number_of_crews', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('time_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('task_type', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('crew_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle_number', models.PositiveIntegerField()),
                ('cycle_time', models.PositiveIntegerField()),
                ('environment_delay', models.IntegerField()),
                ('equipment_delay', models.IntegerField()),
                ('labor_delay', models.IntegerField()),
                ('material_delay', models.IntegerField()),
                ('management_delay', models.IntegerField()),
                ('other_delay', models.IntegerField()),
                ('other_label', models.CharField(blank=True, max_length=255, null=True)),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='particular.particular')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
