# Generated by Django 5.2.5 on 2025-09-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mpdm'),
        ('particular', '0010_workequipment_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainstance',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='particular.projecttype'),
        ),
    ]
