# Generated by Django 5.2.5 on 2025-09-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_datainstance_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_engineer', to='core.engineer'),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='datainstance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
