# Generated by Django 5.2.5 on 2025-09-15 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_datainstance_created_at_datainstance_engineer_and_more'),
        ('particular', '0010_workequipment_equipment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datainstance',
            constraint=models.UniqueConstraint(fields=('date', 'particular', 'collector', 'project'), name='unique_instance'),
        ),
    ]
