# Generated by Django 5.2.5 on 2025-09-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_datainstance_unique_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
